/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/wheel/wheel.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} />
      <mesh geometry={nodes["Node-Mesh_1"].geometry} />
      <mesh geometry={nodes["Node-Mesh_2"].geometry} />
      <mesh geometry={nodes["Node-Mesh_3"].geometry} />
    </group>
  );
}

useGLTF.preload("./models/wheel/wheel.gltf");
