import * as React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Canvas = React.lazy(() => import("@/components/Canvas"));

export default function Home() {
    return (
        <>
            <React.Suspense fallback={null}>
                <Head>
                    <title>NEXT-THREE-STARTER</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Canvas />
            </React.Suspense>
        </>
    );
}
